name: telegram notification

on:
  pull_request:
    branches:
      - main
      

jobs:
  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
    - name: Send Telegram Notification
      run: |
          SENDER_NAME="${{ github.event.pull_request.user.login }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"

          PR_CREATED_AT="${{ github.event.pull_request.created_at }}"

          ACTUAL_TIME="$(date -d "$PR_CREATED_AT" '+%H:%M, %d %b %Y' 2>/dev/null || echo "$PR_CREATED_AT")"

          msg_text="*Pull Request Alert*
          ---

          *Project:* Frontend


          *Sender:* ${SENDER_NAME}


          *Title:* ${PR_TITLE}


          *Source Branch:* ${SOURCE_BRANCH}


          *Target Branch:* ${TARGET_BRANCH}


          *Created At:* ${ACTUAL_TIME}"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_TO }}" \
            -d "parse_mode=Markdown" \
            -d "text=${msg_text}"
